<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>Nim Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nimcfg</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.TODO.nimcfg</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#\s*(TODO|todo)?).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.nimcfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Section declarations</string>
			<key>match</key>
			<string>\[.+\]</string>
			<key>name</key>
			<string>support.type.nimcfg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\@\b(if|elif|else)\b</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.nimcfg</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keywords that affect program control flow or scope.</string>
			<key>end</key>
			<string>\@\b(end)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.nimcfg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_\.]+)\s*(\=)</string>
			<key>comment</key>
			<string>Key declarations</string>
			<key>end</key>
			<string>\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((\d[_\d]*\.[_\d]+([eE][\+\-]?\d[_\d]*)?)|([eE][\+\-]?\d[_\d]*))('[fF](32|64))?</string>
					<key>name</key>
					<string>constant.numeric.float.decimal.nimcfg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(0[xX]\h[_\h]*)('[iIuU](8|16|32|64))?</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.nimcfg</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>For simplicity's sake, we don't enforce floats only having 32 and 64 prefix types.</string>
					<key>match</key>
					<string>\b(0o[0-7][_0-7]*)</string>
					<key>name</key>
					<string>constant.numeric.integer.octal.nimcfg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(0(b|B)[01][_01]*)</string>
					<key>name</key>
					<string>constant.numeric.integer.binary.nimcfg</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\d[_\d]*)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.nimcfg</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Language Constants.</string>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.nimcfg</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>r\"</string>
					<key>comment</key>
					<string>Raw Double Quoted String</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.quoted.double.raw.nimcfg</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\"\"</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.nimcfg</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Double Quoted String</string>
					<key>end</key>
					<string>\"</string>
					<key>name</key>
					<string>string.quoted.double.nimcfg</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\\([abenrclftv\\]|["']|[0-9])|x\h\h)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Single quoted character literal</string>
					<key>match</key>
					<string>\'(\\\d{1,3}|\\?[^\n]?)\'</string>
					<key>name</key>
					<string>string.quoted.single.nimcfg</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.raw.nimcfg</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Value declarations</string>
					<key>match</key>
					<string>\b(.+)\b</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nimcfg</string>
	<key>uuid</key>
	<string>8fb54f5c-6f67-4d13-9dcc-52650ea4cb3e</string>
</dict>
</plist>
